In [1]:
import numpy as np

In [2]:
## Potencia operador ** o power
data = np.array([[1, 2, 3], [4, 5, 6]])

data2 = range(3)

print(data)
print(data2)

# Opciones de array con dimensiones compatibles
print(np.power(data, data2))

[[1 2 3]
 [4 5 6]]
range(0, 3)
[[ 1  2  9]
 [ 1  5 36]]


In [3]:
data_A = np.random.randn(3,2)
print(data_A)

# Multiplicacion de Arrays
print(data * data)

#print(data * data_A) error

# Multiplicar el array(*) no es lo mismo que la multiplicacion de matrices(dot)
print(data_A.dot(data))

[[-1.17716415 -0.84984265]
 [ 0.28851169  1.03829199]
 [-1.89819129 -0.38698098]]
[[ 1  4  9]
 [16 25 36]]
[[-4.57653477 -6.60354157 -8.63054838]
 [ 4.44167964  5.76848331  7.09528699]
 [-3.4461152  -5.73128746 -8.01645973]]


In [4]:
# Operaciones binarias con arrays
a = np.array([1,2,3,4])
b = np.array([4,2,2,4])

print(a == b)
print(a > b)

c = np.array([1,2,3,4])
print(np.array_equal(a, b))
print(np.array_equal(a, c))

[False  True False  True]
[False False  True False]
False
True


In [5]:
#Operaciones Logicas
a = np.array([1,1,0,0], dtype=bool)
b = np.array([1,0,1,0], dtype=bool)

print(np.logical_or(a,b))
print(np.logical_and(a,b))

[ True  True  True False]
[ True False False False]


In [6]:
# Transposicion de Arrays
print(data)
print(data.T)

a = np.arange(9).reshape(3,3)
print(a)

a.T[0,2] = 999
print(a)

print(a.T)

print(a)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[  0   1   2]
 [  3   4   5]
 [999   7   8]]
[[  0   3 999]
 [  1   4   7]
 [  2   5   8]]
[[  0   1   2]
 [  3   4   5]
 [999   7   8]]


In [7]:
# Triangular superior
print(np.triu([[1,2,3],[4,5,6],[7,8,9], [10,11,12]], -1))

print(np.tril([[1,2,3],[4,5,6],[7,8,9], [10,11,12]], -1))

[[ 1  2  3]
 [ 4  5  6]
 [ 0  8  9]
 [ 0  0 12]]
[[ 0  0  0]
 [ 4  0  0]
 [ 7  8  0]
 [10 11 12]]


In [8]:
# Visualizacion de estructura y tipo de datos de un objeto
print(data.shape)

print(data.dtype)

# Arrays a partir de objetos
data1 = [6, 7.5, 8, 0, 1] # Lista
print(data1)
arr1 = np.array(data1)
print(arr1)

(2, 3)
int32
[6, 7.5, 8, 0, 1]
[6.  7.5 8.  0.  1. ]


In [9]:
# Listas de Listas
data2 = [[1,2,3,4], [5,6,7,8]]
print(data2)
arr2 = np.array(data2)
print(arr2)

data2_A = [[1,2,3,4], [5,6,7]]
print(data2_A)
arr2A = np.array(data2_A)
print(arr2A)

[[1, 2, 3, 4], [5, 6, 7, 8]]
[[1 2 3 4]
 [5 6 7 8]]
[[1, 2, 3, 4], [5, 6, 7]]
[list([1, 2, 3, 4]) list([5, 6, 7])]


In [10]:
# Inicializar con ceros
print(np.zeros(10))
print(np.zeros((3,6)))

print(np.ones((3,6)))

# Creacion de un array con ceros o basura numerica
print(np.empty((2,3,2)))

print(np.arange(15))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
[[[9.83453330e-312 2.47032823e-322]
  [0.00000000e+000 0.00000000e+000]
  [0.00000000e+000 1.61590357e+184]]

 [[4.97407142e-091 1.10587272e+165]
  [2.32597275e-057 4.66442089e-062]
  [3.99910963e+252 1.46030983e-319]]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [11]:
# Crear arrays de un tipo de dato especifico
arr1 = np.array([1,2,3], dtype=np.float64)
arr2 = np.array([1,2,3], dtype=np.int32)

print(arr1)
print(arr2)

print(arr1.dtype)
print(arr2.dtype)

arr2_ABC = np.array([1,2,3], dtype=np.complex128)
print(arr2_ABC)

print(arr2_ABC.dtype)

[1. 2. 3.]
[1 2 3]
float64
int32
[1.+0.j 2.+0.j 3.+0.j]
complex128


In [12]:
# Convertir a tipo de datos
arr = np.array([1,2,3,4,5])
print(arr.dtype)

float_arr = arr.astype(np.float64)
print(float_arr)

char  = float_arr.astype(np.string_)
print(char)

int32
[1. 2. 3. 4. 5.]
[b'1.0' b'2.0' b'3.0' b'4.0' b'5.0']


In [13]:
arr_A = np.array([1,2,3,4,5])

string_arr_A = arr_A.astype(np.string_)
print(string_arr_A)
print(string_arr_A.dtype)

arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
print(arr)
print(arr.astype(np.int32))

[b'1' b'2' b'3' b'4' b'5']
|S11
[ 3.7 -1.2 -2.6  0.5 12.9 10.1]
[ 3 -1 -2  0 12 10]


In [14]:
# importacion desde ficheros o como cadenas de string
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)
print(numeric_strings)

print(numeric_strings.astype(float))

numeric_strings_A = np.array(['1.25', '-9.6', '42'], dtype=np.string_)
numeric_strings_A = numeric_strings_A.astype(float)
array_A = numeric_strings_A * 2
print(array_A)

[b'1.25' b'-9.6' b'42']
[ 1.25 -9.6  42.  ]
[  2.5 -19.2  84. ]


In [15]:
# Extraer datos
arr = np.array([0,1,2,3,4,120,12,12,8,9])
print(arr)

print(arr[5])

arr[5:8] = 12
arr[5:8] = arr[5:8] * 2
print(arr[5:8])

arr_slice = arr[5:8]
print(arr_slice)

[  0   1   2   3   4 120  12  12   8   9]
120
[24 24 24]
[24 24 24]


In [16]:
# Copias
arr = np.arange(10)
print(arr)
arr_AB = np.copy(arr)
print(arr_AB)
arr[5:8] = 12

print(arr)
print(arr_AB)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[ 0  1  2  3  4 12 12 12  8  9]
[0 1 2 3 4 5 6 7 8 9]


In [17]:
# Shallow y Deep copy

a = np.array([1, 'm', [2,3,4]], dtype=object)
import copy
c = copy.deepcopy(a)

print(a)
print(c)

c[2][0] = 10
print(c)

# Otros metodos (ndarray.copy)

[1 'm' list([2, 3, 4])]
[1 'm' list([2, 3, 4])]
[1 'm' list([10, 3, 4])]


In [26]:
# Arrays Multidimensionales
arr2d = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(arr2d)

print(arr2d[0])

print(arr2d[0][2])

arr3d = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]])

print(arr3d)

print(arr3d[0])
print(arr3d[0][0])
print(arr3d[0][0][0])
print(arr3d[0,1,0])

print(arr2d)
print(arr2d[1:3])
print(arr2d[:2])
print(arr2d[:2,1:])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3]
3
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[[1 2 3]
 [4 5 6]]
[1 2 3]
1
4
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]]
[[2 3]
 [5 6]]
[4 7]


In [38]:
print(arr2d[1,0:2])
print(arr2d[0:3,0])

# colocar a cero las columnas 1 y 2
print(arr2d)
arr2d[0:3,1:3] = 0
print(arr2d)
arr2d[:,1:] = 0

[4 0]
[1 4 7]
[[1 0 0]
 [4 0 0]
 [7 0 0]]
[[1 0 0]
 [4 0 0]
 [7 0 0]]


In [48]:
# Metodos matematicos y Financieros
arr = np.random.randn(5,4)
print(arr)

print(np.mean(arr))
print(arr.mean())

# media de cada fila
print(arr.mean(axis=1))

# media de cada columna
print(arr.mean(axis=0))

print('----')
print(arr)
print(arr.sum(axis=1))
print(arr.sum(axis=0))

[[ 1.04951988 -0.37172305 -0.32986856  1.55294063]
 [-1.62900752  0.53713367 -0.31999848  0.4784137 ]
 [ 0.77879952  2.05823226  1.73528109  0.98444733]
 [ 0.48085448 -0.96498566  0.50450375  0.73833786]
 [-0.5039244  -0.3458607  -0.13001611 -0.4376352 ]]
0.29327222563817756
0.29327222563817756
[ 0.47521723 -0.23336465  1.38919005  0.18967761 -0.3543591 ]
[0.03524839 0.18255931 0.29198034 0.66330087]
----
[[ 1.04951988 -0.37172305 -0.32986856  1.55294063]
 [-1.62900752  0.53713367 -0.31999848  0.4784137 ]
 [ 0.77879952  2.05823226  1.73528109  0.98444733]
 [ 0.48085448 -0.96498566  0.50450375  0.73833786]
 [-0.5039244  -0.3458607  -0.13001611 -0.4376352 ]]
[ 1.9008689  -0.93345862  5.5567602   0.75871043 -1.4174364 ]
[0.17624197 0.91279653 1.45990169 3.31650433]


In [53]:
arr = np.array([0,1,2,3,4,5,6,7])

print(arr.cumsum())
print(arr.cumprod())

arr = np.array([[0,1,2],[3,4,5],[6,7,8]])
print(arr)

# suma acumulada por filas
print(arr.cumsum(axis=1))
# suma acumulada por columnas
print(arr.cumsum(axis=0))

[ 0  1  3  6 10 15 21 28]
[0 0 0 0 0 0 0 0]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 0  1  3]
 [ 3  7 12]
 [ 6 13 21]]
[[ 0  1  2]
 [ 3  5  7]
 [ 9 12 15]]


In [64]:
# Ordenacion de arrays
arr = np.random.randn(6)
print(arr)

print(arr.sort())
print(arr)

arr = np.random.randn(5,3)
print(arr)
arr.sort(1)
print(arr)

arr[::-1].sort()
print(arr[::-1].sort())

[-0.80963058 -0.11399405 -1.17695271 -0.19360559  0.49792649  0.45235395]
None
[-1.17695271 -0.80963058 -0.19360559 -0.11399405  0.45235395  0.49792649]
[[-1.9189775  -0.28681102  0.61974544]
 [ 0.70171941 -0.04114765 -0.04242052]
 [ 1.55137065  1.53509883  0.88450423]
 [ 1.2492539   0.14527521  1.61248735]
 [-1.79012744 -0.23574844  0.23092195]]
[[-1.9189775  -0.28681102  0.61974544]
 [-0.04242052 -0.04114765  0.70171941]
 [ 0.88450423  1.53509883  1.55137065]
 [ 0.14527521  1.2492539   1.61248735]
 [-1.79012744 -0.23574844  0.23092195]]
None
